# Generated by Django 5.1.2 on 2026-06-04 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_initial"),
        ("orders", "0003_order_applied_credit_amount_and_more"),
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("business_cancellation", "Business cancellation"),
                            ("referral", "Referral (Phase 2)"),
                            ("promo", "Admin promo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Bonus credit",
                "verbose_name_plural": "Bonus credits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("payphone", "PayPhone"),
                            ("de_una", "DeUna"),
                            ("kushki", "Kushki"),
                            ("stripe", "Stripe"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("provider_event_id", models.CharField(max_length=128)),
                ("event_type", models.CharField(blank=True, max_length=80)),
                ("received_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_provider_transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refund_pending", "Refund pending"),
                    ("refunded", "Refunded"),
                    ("refund_failed", "Refund failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_transaction_id", ""), _negated=True),
                fields=("provider", "provider_transaction_id"),
                name="uniq_provider_transaction_id_per_provider",
            ),
        ),
        migrations.AddField(
            model_name="bonuscredit",
            name="redeemed_in_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redeemed_bonus_credits",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="bonuscredit",
            name="source_business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bonus_credits_funded",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="bonuscredit",
            name="source_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bonus_credits_granted",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="bonuscredit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bonus_credits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookeventlog",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_event_id"), name="uniq_webhook_event_per_provider"
            ),
        ),
        migrations.AddIndex(
            model_name="bonuscredit",
            index=models.Index(
                fields=["user", "redeemed_at"], name="payments_bo_user_id_f2784b_idx"
            ),
        ),
    ]
