# Generated by Django 5.1.2 on 2026-05-23 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllergenTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("label_es", models.CharField(max_length=80)),
                ("label_en", models.CharField(blank=True, max_length=80)),
                ("icon_name", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "verbose_name": "Allergen tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("surprise", "Surprise bag"), ("specific", "Specific items")],
                        default="surprise",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                (
                    "extra_image_urls",
                    models.JSONField(blank=True, default=list, help_text="Used by specific bags"),
                ),
                ("original_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                ("quantity_total", models.PositiveIntegerField(default=0)),
                ("pickup_window_start", models.DateTimeField()),
                ("pickup_window_end", models.DateTimeField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_suspended_meal_eligible", models.BooleanField(default=False)),
                (
                    "allergen_warnings",
                    models.ManyToManyField(blank=True, related_name="bags", to="bags.allergentag"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
