# Generated by Django 5.1.2 on 2026-05-23 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bags", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bag",
            name="dietary_tags",
            field=models.ManyToManyField(blank=True, related_name="bags", to="users.dietarytag"),
        ),
        migrations.AddIndex(
            model_name="bag",
            index=models.Index(
                fields=["is_active", "pickup_window_end"], name="bags_bag_is_acti_e6c4d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bag",
            index=models.Index(
                fields=["business_location", "is_active"], name="bags_bag_busines_55ec88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bag",
            constraint=models.CheckConstraint(
                condition=models.Q(("pickup_window_end__gt", models.F("pickup_window_start"))),
                name="bag_pickup_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="bag",
            constraint=models.CheckConstraint(
                condition=models.Q(("sale_price__gte", Decimal("0"))),
                name="bag_sale_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bag",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_price__gt", Decimal("0"))),
                name="bag_original_price_positive",
            ),
        ),
    ]
