# Generated by Django 5.1.2 on 2026-06-12 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bags", "0003_initial"),
        ("businesses", "0002_initial"),
        ("users", "0002_user_email_verified_at_user_is_email_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "type",
                    models.CharField(
                        choices=[("surprise", "Surprise bag"), ("specific", "Specific items")],
                        default="surprise",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("original_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_suspended_meal_eligible", models.BooleanField(default=False)),
                (
                    "allergen_warnings",
                    models.ManyToManyField(
                        blank=True, related_name="bag_templates", to="bags.allergentag"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bag_templates",
                        to="businesses.business",
                    ),
                ),
                (
                    "dietary_tags",
                    models.ManyToManyField(
                        blank=True, related_name="bag_templates", to="users.dietarytag"
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "name"), name="uniq_bag_template_name_per_business"
                    )
                ],
            },
        ),
    ]
