# Generated by Django 5.1.2 on 2026-05-23 10:48

import apps.orders.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "opened_by",
                    models.CharField(
                        choices=[("consumer", "Consumer"), ("business", "Business")], max_length=10
                    ),
                ),
                ("reason", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("evidence_urls", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under review"),
                            ("resolved_refund", "Resolved — refund"),
                            ("resolved_no_refund", "Resolved — no refund"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("original_price_snapshot", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sale_price_snapshot", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_paid", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8),
                ),
                (
                    "business_payout_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8),
                ),
                (
                    "pickup_code",
                    models.CharField(
                        default=apps.orders.models._generate_pickup_code, max_length=4
                    ),
                ),
                (
                    "pickup_qr_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("paid", "Paid"),
                            ("ready_for_pickup", "Ready for pickup"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("consumer", "Consumer"),
                            ("business", "Business"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payphone", "PayPhone"),
                            ("de_una", "DeUna"),
                            ("kushki", "Kushki"),
                            ("stripe", "Stripe"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_provider_ref", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
