# Generated by Django 5.1.2 on 2026-05-23 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bags", "0003_initial"),
        ("businesses", "0002_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="bag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="bags.bag"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="business_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="businesses.businesslocation",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disputes",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["consumer", "status"], name="orders_orde_consume_8d31ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["business_location", "status"], name="orders_orde_busines_c68e90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["pickup_code"], name="orders_orde_pickup__550cbd_idx"),
        ),
    ]
