# Generated by Django 5.1.2 on 2026-06-04 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="applied_credit_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="donate_as_suspended_meal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending payment"),
                    ("paid", "Paid"),
                    ("ready_for_pickup", "Ready for pickup"),
                    ("completed", "Completed"),
                    ("pending_refund", "Pending refund"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
