# Generated by Django 5.1.2 on 2026-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_applied_credit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pin_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="pin_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="qr_consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
