# Generated by Django 5.1.2 on 2026-05-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adcampaign",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ad_campaigns",
                to="businesses.business",
            ),
        ),
    ]
