/**
 * La Yapa — Design tokens (single source of truth).
 *
 * Consumed by:
 *   • apps/mobile  → as TypeScript constants via ThemeProvider
 *   • apps/admin   → as CSS variables generated by `generateCssVariables()` and
 *                    mapped into Tailwind's `colors`/`fontFamily` config.
 *
 * Brand reference: MASTER_VISION.md → "Brand Identity".
 */

// ---------------------------------------------------------------------------
// Palette (raw, untoken colors). Used to build semantic light/dark themes.
// ---------------------------------------------------------------------------
export const palette = {
  // Primary
  verdeParamo: '#2D6A4F',
  terracottaInti: '#D97757',
  amarilloSol: '#F4C430',

  // Neutrals (light surface family)
  algodon: '#FAF6F0',
  blancoPuro: '#FFFFFF',
  tierra: '#1B2D2A',
  niebla: '#6B7B78',
  piedra: '#E5E1D8',

  // Neutrals (dark surface family)
  darkBg: '#0F1A18',
  darkSurface: '#1A2A26',
  darkBorder: '#2A3D38',
  darkText: '#E8E5DE',

  // Semantic
  successEco: '#52B788',
  warning: '#F4A261',
  error: '#C44536',
  info: '#4A90E2',

  // Utility
  transparent: 'transparent',
  black: '#000000',
  white: '#FFFFFF',
} as const;

export type PaletteToken = keyof typeof palette;

// ---------------------------------------------------------------------------
// Semantic color schemes. ALL components should consume these, never `palette.*`
// directly, so light/dark mode just works.
// ---------------------------------------------------------------------------
export interface ColorScheme {
  // Surfaces
  background: string;
  surface: string;
  surfaceMuted: string;
  overlay: string;

  // Borders / dividers
  border: string;
  borderStrong: string;

  // Text
  text: string;
  textMuted: string;
  textInverse: string;
  textOnPrimary: string;

  // Brand
  primary: string;
  primaryHover: string;
  primaryActive: string;
  primarySoft: string;

  secondary: string;
  secondaryHover: string;
  secondarySoft: string;

  accent: string;
  accentSoft: string;

  // Semantic
  success: string;
  successSoft: string;
  warning: string;
  warningSoft: string;
  error: string;
  errorSoft: string;
  info: string;
  infoSoft: string;

  // Interactive
  focusRing: string;
}

export const lightScheme: ColorScheme = {
  background: palette.algodon,
  surface: palette.blancoPuro,
  surfaceMuted: '#F3EEE5',
  overlay: 'rgba(27, 45, 42, 0.55)',

  border: palette.piedra,
  borderStrong: '#C9C2B3',

  text: palette.tierra,
  textMuted: palette.niebla,
  textInverse: palette.blancoPuro,
  textOnPrimary: palette.blancoPuro,

  primary: palette.verdeParamo,
  primaryHover: '#26583F',
  primaryActive: '#1F4634',
  primarySoft: '#DCE9E1',

  secondary: palette.terracottaInti,
  secondaryHover: '#C46647',
  secondarySoft: '#F5DACE',

  accent: palette.amarilloSol,
  accentSoft: '#FBE9A6',

  success: palette.successEco,
  successSoft: '#D6EFE0',
  warning: palette.warning,
  warningSoft: '#FBE3CC',
  error: palette.error,
  errorSoft: '#F1CFC9',
  info: palette.info,
  infoSoft: '#D2E2F4',

  focusRing: palette.verdeParamo,
};

export const darkScheme: ColorScheme = {
  background: palette.darkBg,
  surface: palette.darkSurface,
  surfaceMuted: '#22332F',
  overlay: 'rgba(0, 0, 0, 0.65)',

  border: palette.darkBorder,
  borderStrong: '#3A4F49',

  text: palette.darkText,
  textMuted: '#9BA8A4',
  textInverse: palette.tierra,
  textOnPrimary: palette.darkText,

  primary: '#4F9275',
  primaryHover: '#5FA585',
  primaryActive: '#6FB995',
  primarySoft: '#1F3A2E',

  secondary: '#E08B6F',
  secondaryHover: '#E89A82',
  secondarySoft: '#3A2620',

  accent: palette.amarilloSol,
  accentSoft: '#3A3320',

  success: palette.successEco,
  successSoft: '#1F3A2A',
  warning: palette.warning,
  warningSoft: '#3A2A1C',
  error: '#D4604F',
  errorSoft: '#3A1F1A',
  info: '#6BA7E8',
  infoSoft: '#1A2A3A',

  focusRing: '#5FA585',
};

export type ThemeMode = 'light' | 'dark';

export const schemes: Record<ThemeMode, ColorScheme> = {
  light: lightScheme,
  dark: darkScheme,
};

// ---------------------------------------------------------------------------
// Typography
// ---------------------------------------------------------------------------
export const fonts = {
  heading: 'Poppins',
  body: 'Inter',
  accent: 'Fraunces',
  mono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
} as const;

export const fontWeights = {
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
} as const;

/**
 * Type scale — fontSize/lineHeight in pixels.
 * Tailwind consumes the [size, { lineHeight }] tuple shape.
 */
export const typeScale = {
  h1: { fontSize: 32, lineHeight: 40, fontWeight: fontWeights.bold, fontFamily: fonts.heading },
  h2: { fontSize: 24, lineHeight: 32, fontWeight: fontWeights.semibold, fontFamily: fonts.heading },
  h3: { fontSize: 20, lineHeight: 28, fontWeight: fontWeights.semibold, fontFamily: fonts.heading },
  body: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: fontWeights.regular,
    fontFamily: fonts.body,
  },
  bodyStrong: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: fontWeights.medium,
    fontFamily: fonts.body,
  },
  small: { fontSize: 14, lineHeight: 20, fontWeight: fontWeights.regular, fontFamily: fonts.body },
  caption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: fontWeights.medium,
    fontFamily: fonts.body,
  },
} as const;

export type TypeScaleToken = keyof typeof typeScale;

// ---------------------------------------------------------------------------
// Spacing — 4px base, named scale per master vision.
// ---------------------------------------------------------------------------
export const spacing = {
  0: 0,
  1: 4,
  2: 8,
  3: 12,
  4: 16,
  5: 20,
  6: 24,
  8: 32,
  10: 40,
  12: 48,
  16: 64,
} as const;

export type SpacingToken = keyof typeof spacing;

// ---------------------------------------------------------------------------
// Border radii
// ---------------------------------------------------------------------------
export const radii = {
  none: 0,
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  full: 9999,
} as const;

export type RadiusToken = keyof typeof radii;

// ---------------------------------------------------------------------------
// Shadows / elevation (RN-friendly + CSS friendly)
// ---------------------------------------------------------------------------
export const shadows = {
  none: {
    css: 'none',
    rn: {
      shadowColor: 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
  },
  sm: {
    css: '0 1px 2px rgba(27, 45, 42, 0.08)',
    rn: {
      shadowColor: '#1B2D2A',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1,
    },
  },
  md: {
    css: '0 4px 12px rgba(27, 45, 42, 0.10)',
    rn: {
      shadowColor: '#1B2D2A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 3,
    },
  },
  lg: {
    css: '0 12px 32px rgba(27, 45, 42, 0.14)',
    rn: {
      shadowColor: '#1B2D2A',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.14,
      shadowRadius: 32,
      elevation: 8,
    },
  },
} as const;

export type ShadowToken = keyof typeof shadows;

// ---------------------------------------------------------------------------
// Motion
// ---------------------------------------------------------------------------
export const motion = {
  duration: {
    fast: 120,
    base: 200,
    slow: 320,
  },
  easing: {
    standard: 'cubic-bezier(0.2, 0, 0, 1)',
    emphasized: 'cubic-bezier(0.3, 0, 0, 1)',
    decelerate: 'cubic-bezier(0, 0, 0.2, 1)',
  },
} as const;

// ---------------------------------------------------------------------------
// Z-index
// ---------------------------------------------------------------------------
export const zIndex = {
  base: 0,
  dropdown: 10,
  sticky: 20,
  modal: 100,
  toast: 200,
  tooltip: 300,
} as const;

// ---------------------------------------------------------------------------
// Aggregated theme object for the mobile ThemeProvider.
// ---------------------------------------------------------------------------
export interface Theme {
  mode: ThemeMode;
  colors: ColorScheme;
  fonts: typeof fonts;
  fontWeights: typeof fontWeights;
  type: typeof typeScale;
  spacing: typeof spacing;
  radii: typeof radii;
  shadows: typeof shadows;
  motion: typeof motion;
  zIndex: typeof zIndex;
}

export const buildTheme = (mode: ThemeMode): Theme => ({
  mode,
  colors: schemes[mode],
  fonts,
  fontWeights,
  type: typeScale,
  spacing,
  radii,
  shadows,
  motion,
  zIndex,
});

export const lightTheme = buildTheme('light');
export const darkTheme = buildTheme('dark');

// ---------------------------------------------------------------------------
// CSS-variable generator for the admin (Tailwind reads `var(--color-…)`).
// ---------------------------------------------------------------------------
const kebab = (s: string): string => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

const schemeToCssVars = (scheme: ColorScheme): Record<string, string> => {
  const vars: Record<string, string> = {};
  for (const [key, value] of Object.entries(scheme)) {
    vars[`--color-${kebab(key)}`] = value;
  }
  return vars;
};

export const cssVariables = {
  light: schemeToCssVars(lightScheme),
  dark: schemeToCssVars(darkScheme),
} as const;

/** Render a CSS string suitable for embedding in a global stylesheet. */
export const generateCssVariables = (): string => {
  const block = (selector: string, vars: Record<string, string>): string => {
    const lines = Object.entries(vars)
      .map(([k, v]) => `  ${k}: ${v};`)
      .join('\n');
    return `${selector} {\n${lines}\n}`;
  };
  return [
    block(':root', cssVariables.light),
    block('.dark, [data-theme="dark"]', cssVariables.dark),
  ].join('\n\n');
};
