# Generated by Django 5.1.2 on 2026-05-23 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRepProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=3, default=Decimal("0.020"), max_digits=4),
                ),
                (
                    "businesses_onboarded",
                    models.ManyToManyField(
                        blank=True, related_name="onboarded_by_reps", to="businesses.business"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales rep profile",
            },
        ),
    ]
