# Generated by Django 5.1.2 on 2026-05-23 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("icon_url", models.URLField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("saver", "Saver"),
                            ("streak", "Streak"),
                            ("community", "Community"),
                            ("explorer", "Explorer"),
                            ("premium", "Premium"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=12,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"meals_saved": 10, "category": "bakery"}',
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "reward_credit_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("bronce", "Bronce"),
                            ("plata", "Plata"),
                            ("oro", "Oro"),
                            ("cotopaxi", "Cotopaxi"),
                            ("galapagos", "Galápagos"),
                        ],
                        default="bronce",
                        max_length=12,
                    ),
                ),
                ("xp_total", models.PositiveIntegerField(default=0)),
                ("meals_rescued", models.PositiveIntegerField(default=0)),
                (
                    "kg_saved",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "co2_saved_kg",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "money_saved_usd",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                ("current_streak_weeks", models.PositiveSmallIntegerField(default=0)),
                ("longest_streak_weeks", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "User level",
                "ordering": ["-xp_total"],
            },
        ),
    ]
