# Generated by Django 5.1.2 on 2026-05-23 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImpactStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meals_rescued", models.PositiveIntegerField(default=0)),
                (
                    "kg_food_saved",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "co2_kg_saved",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "money_saved",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Impact stat",
            },
        ),
    ]
