# Generated by Django 5.1.2 on 2026-05-23 10:48

import apps.geo.fields
import encrypted_model_fields.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("bakery", "Bakery"),
                            ("supermarket", "Supermarket"),
                            ("hotel", "Hotel"),
                            ("mercado", "Mercado"),
                            ("farmer", "Farmer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("formal", "Formal (RUC required)"),
                            ("informal", "Informal (mercado/farmer)"),
                        ],
                        default="formal",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payout_frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[("bank_transfer", "Bank transfer"), ("de_una", "DeUna")],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "bank_account",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, default=""),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=3, default=Decimal("0.180"), max_digits=4),
                ),
            ],
            options={
                "verbose_name_plural": "Businesses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text='e.g. "Sucursal Centro"', max_length=140)),
                ("address", models.CharField(max_length=255)),
                ("location", apps.geo.fields.PointField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("hours_of_operation", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["business__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ruc_number", models.CharField(blank=True, max_length=20)),
                ("ruc_document_url", models.URLField(blank=True)),
                ("cedula_number", models.CharField(blank=True, max_length=20)),
                ("cedula_document_url", models.URLField(blank=True)),
                ("selfie_with_cedula_url", models.URLField(blank=True)),
                ("permiso_funcionamiento_url", models.URLField(blank=True)),
                ("arcsa_url", models.URLField(blank=True)),
                ("bank_proof_url", models.URLField(blank=True)),
                ("business_photo_url", models.URLField(blank=True)),
                ("food_safety_terms_accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Business verification",
                "verbose_name_plural": "Business verifications",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
