# Generated by Django 5.1.2 on 2026-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
    ]
