# Generated by Django 5.1.2 on 2026-05-23 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bags", "0002_initial"),
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspendedMealClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("beneficiary_notes", models.TextField(blank=True)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suspended_claims",
                        to="businesses.businesslocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.CreateModel(
            name="SuspendedMealDonation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("claimed", "Claimed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("is_anonymous", models.BooleanField(default=True)),
                (
                    "bag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific bag, or null for the general pool.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspended_donations",
                        to="bags.bag",
                    ),
                ),
                (
                    "claimed_by_business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_donations",
                        to="businesses.businesslocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
