# Generated by Django 5.1.2 on 2026-05-23 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suspended_meals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suspendedmealdonation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="suspendedmealclaim",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="suspended_meals.suspendedmealdonation",
            ),
        ),
    ]
